webpackJsonp([0xec7cffbd61ee2800],{"./node_modules/json-loader/index.js!./.cache/json/computer-science-error-handling.json":function(e,n){e.exports={data:{markdownRemark:{html:'<h2>Error Handling</h2>\n<p>Error Handling, and to a larger extent, Exception Handling, are programs written into methods to return important information about the manipulation of data. Error handling is often used alongside Promises and Callbacks.\nError handling is very important thing every developer should care about while doing programming. Here I’ll explain how to handle errors which occurs run-time using try-catch block with an example in C# programs. Try-catch block available in all the major programming languages and has similar syntax as well.</p>\n<h3>How try-catch block works.</h3>\n<p>Whatever the code available in the try block executes as similar like the source code executes out of try block. Try block means that your trying to execute some code which may throw exceptions. When a code in try block throws any exception, the same can handle/catch by catch block. The advantages of having the try-catch block is, it make sure that unexpected termination of program will not happen at run time.</p>\n<p>Try-catch block syntax included an optional block called finally. Which gets executed always, whether the try blocks throws error or not.</p>\n<p>Below I’ve given a program which handles the divide by zero exception using predefined class in C# library. Exception is the base class for all the exception.</p>\n<div class="gatsby-highlight">\n      <pre class="language-c#"><code>using System;\nnamespace ErrorHandling\n{\n   class DivideByZero\n    {\n       int result;\n       DivideByZero()\n       {\n          result = 0;\n       }\n       public void division(int num1, int num2)\n       {\n          try\n          {\n             result = num1 / num2;\n          }\n          catch (DivideByZeroException e)\n          {\n             Console.WriteLine("Exception caught: {0}", e);\n          }\n          catch(Exception ex)\n          {\n              Console.WriteLine("Exception caught: {0}", ex);\n          }\n          finally\n          {\n             Console.WriteLine("Result: {0}", result);\n          }\n       }\n       static void Main(string[] args)\n       {\n          DivideByZero d = new DivideByZero();\n          d.division(10, 0);\n          Console.ReadKey();\n       }\n    }\n }</code></pre>\n      </div>\n<ul>\n<li>In the above program passing 0 as second parameter will throw DivideByZeroExceptions. </li>\n<li>This exception will handle by the catch block which has DivideByZeroException class. If any exceptions other than DivideByZeroExceptions occurs it will handle by Exception catch block.</li>\n</ul>\n<p> Exception is the base class for all the exceptions class available in C# library. Even if you want to write your own exception you have to inherits Exception base class into your program.</p>\n<h4>More Information:</h4>\n<!-- Please add any articles you think might be helpful to read before writing the article -->\n<p><a href="https://quizlet.com/135129010/computer-science-error-handling-flash-cards/">https://quizlet.com/135129010/computer-science-error-handling-flash-cards/</a>\n<a href="https://en.wikipedia.org/wiki/Exception_handling">https://en.wikipedia.org/wiki/Exception_handling</a></p>',fields:{slug:"/computer-science/error-handling/"},frontmatter:{title:"Error Handling"}}},pathContext:{slug:"/computer-science/error-handling/"}}}});
//# sourceMappingURL=path---computer-science-error-handling-0de53e236020c13f10ac.js.map